/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operacion {
	float a;
	float b;
	char operador;
};
typedef struct operacion operacion;

#define CALCULADORA_PROG 0x31234567
#define CALCULADORA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define calcular 1
extern  float * calcular_1(operacion *, CLIENT *);
extern  float * calcular_1_svc(operacion *, struct svc_req *);
extern int calculadora_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calcular 1
extern  float * calcular_1();
extern  float * calcular_1_svc();
extern int calculadora_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operacion (XDR *, operacion*);

#else /* K&R C */
extern bool_t xdr_operacion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
