/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "registro_alumnos.h"


void
registro_alumnos_1(char *host)
{
	CLIENT *clnt;
	bool_t  *result_1;
	alumno  registrar_alumno_1_arg;
	resultado_busqueda  *result_2;
	busqueda  buscar_alumno_1_arg;
	bool_t  *result_3;
	alumno  actualizar_alumno_1_arg;
	bool_t  *result_4;
	int  eliminar_alumno_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, REGISTRO_ALUMNOS, REGISTRO_ALUMNOS_V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registrar_alumno_1(&registrar_alumno_1_arg, clnt);
	if (result_1 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = buscar_alumno_1(&buscar_alumno_1_arg, clnt);
	if (result_2 == (resultado_busqueda *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = actualizar_alumno_1(&actualizar_alumno_1_arg, clnt);
	if (result_3 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = eliminar_alumno_1(&eliminar_alumno_1_arg, clnt);
	if (result_4 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	registro_alumnos_1 (host);
exit (0);
}
