/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "registro_alumnos.h"

bool_t *
registrar_alumno_1_svc(alumno *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

resultado_busqueda *
buscar_alumno_1_svc(busqueda *argp, struct svc_req *rqstp)
{
	static resultado_busqueda  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
actualizar_alumno_1_svc(alumno *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

bool_t *
eliminar_alumno_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}
