/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "registro_alumnos.h"

bool_t
xdr_alumno (XDR *xdrs, alumno *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nombre, MAX_NOMBRE))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->apellido, MAX_APELLIDO))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->edad))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->curso, MAX_CURSO))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_busqueda (XDR *xdrs, busqueda *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->nombre, MAX_NOMBRE))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->apellido, MAX_APELLIDO))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->curso, MAX_CURSO))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_resultado_busqueda (XDR *xdrs, resultado_busqueda *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cantidad))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->datos.datos_val, (u_int *) &objp->datos.datos_len, ~0,
		sizeof (alumno), (xdrproc_t) xdr_alumno))
		 return FALSE;
	return TRUE;
}
